### ISSUE TITLE
Ideas to improve Html-Tag-objects

### ISSUE THREAD

**Issue by broeser** [brick/brick#1]
Hi there!

I'm currently in a situation where I'd like to generate PHP objects for HTML Tags. I thought „there must be thousands of libraries doing exactly that“ – Nope. All of the projects I could find are unmaintained, broken or poorly documented.

So I was glad to find the files under brick/brick/src/Html which seem like a great start.

Before I start working with that, I wanted to ask if you accept pull requests and if there are any contributing guidelines. If you see this incubator more as a private playground and don't want any outsider interference, I can understand and I'll just write my own Tag library.

These are the ideas I'd like to work on:
1. Text node (text between opening and closing tag) support: Having a TextNode-class is great, because that way both Tags and TextNodes can implement the same interface (or inherit from the same class, I don't know yet) and methods (e.g. generators for other Tags) can accept "Tags or TextNodes"
2. A HTML5-Tag-factory/generator that takes a tag name and either returns a SelfClosingTag (for area, base, br, col, command, embed, hr, img, input, keygen, link, meta, param, source, track, wbr) or a ContainerTag (for all other tags); I think I'd even call it "Tag" or something short like that (and maybe rename the current Tag-class?) It would avoid the bloat of having one class for each available Tag while it wouldn't be necessary to change much code in case the HTML spec changes and certain tags become self-closing/container tags
3. An array of Tags (or TextNodes) as content of a ContainerTag (instead of a string) would be great. That way, tags could be changed/removed before rendering etc. The render()-method could just concatenate the array before returning the string
4. I don't know how useful it is in a real world use-case, but I'd like to throw Exceptions when passing invalid parameters (non-strings for attributes etc.)

Any thoughts? :)

Yours,
Benedict

**Comment by BenMorel** [comment]
Hi Benedict, I'm very much open to PRs, it's always good to get fresh ideas!

I wrote this tag library as a foundation for [brick/form](https://github.com/brick/form), but I've always considered it as half-baked, that's why it's still in the incubator.

About your suggestions:
1. I'm a bit torn TBH; it might be cleaner conceptually speaking, but at the same time it feels cumbersome and impractical to force wrapping each string in a TextNode object. And what about uses cases when you already have valid HTML to set as content?  
   An alternative would be to only accept HTML strings: `addContent(string $html)`. `Tag` already implements the `__toString()` method, so you could pass a `Tag` as content, or any valid HTML string. And we could create an optional TextNode class, that would simply call `htmlspecialchars()` in `__toString()`, although I'm not sure this is enough to justify the addition of this class.
2. This is interesting, but do you have a use case? Usually, when you create a Tag, you know if it's a self-closing tag or not. My personal experience when writing the form library was that the issue was not to know whether the tag is self-closing or not (an `<input>` will always be self-closing, a `<textarea>` will never be; you usually know what you're dealing with), but whether we are outputting HTML or XHTML (and whether to write `<input>` or `<input />`).
3. This is probably a good idea, although I fail to see a real value in allowing to _remove_ contents (and how you're planning to select the content to remove).
4. This may not be necessary, as we're all going to transition to PHP 7 soon, and PHP 7 has static type hinting, and throws exceptions when passing invalid types.

As a final note, if you're going to invest time on this, I would suggest you have a look at similar libraries in other programming languages. PHP may not have good libraries yet, but other languages might, and there may be good ideas to get there.

**Comment by jkuchar** [comment]
You can pick some inspiration from [nette/html](https://doc.nette.org/en/2.3/html-elements) ( [github](https://github.com/nette/utils/blob/master/src/Utils/Html.php) ) which is being used in [nette/forms](https://github.com/nette/forms).

**Comment by broeser** [comment]
I'm also interested in input sanitization/input validation, see [broeser/sanitor](https://github.com/broeser/sanitor) and [broeser/wellid](http://broeser.github.io/wellid/), I'd be happy if you had a look. My feeble attempts at form building can be found here: [broeser/feeld](https://github.com/broeser/feeld), however I have a very different focus (my final goal is being able to use the same data model and validation rules in different representations, e. g. Web form, PDF form, CLI, desktop app (GTK?), ... which I realize is not a very common use case.

Back to topic:

@BenMorel 
1. Yes, it makes more sense if usage of TextNode is optional. Whether to accept a string or a TagOrTextNode-whatever depends on whether 3. is also implemented or not.
2. The use case would be the rather abstract "if the HTML specification changes, there is less code to change" – so it's probably not an important point
3. Selecting the content for removal could be done by attribute (e. g. "remove all content that has the attribute id set to "foo" or remove all content that has the class set to "bar"). It certainly increases overall complexity though.
4. As of now, PHP 5.5 and 5.6 are still actively maintained, but I see your point.

I will have a look at libraries in other languages.

@jkuchar 
I'll have a look, thank you!

**Comment by BenMorel** [comment]
@broeser 
1. The thing is, it is mandatory IMO to accept raw HTML strings anyway, not just objects; otherwise you're strongly limiting the usefulness of the library. And if you do, then you can either accept a string (and typecast objects implicitly), or introduce an interface and wrap your HTML strings in an object. I think this is overkill here, just like it is overkill to force wrapping raw text in a TextNode object.
2. If the HTML specification changes, I doubt it will change the self-closingness of the tag. And if it ever does, you might have to change your code anyway: a `ContainerTag` becoming a `SelfClosingTag` would miss the methods to add content.
3. It does increase the complexity quite a lot, especially if you decide to accept raw HTML strings as content: you would have to parse these strings to be able to remove content based on attributes. I think this is unnecessary complexity for a tag generation library.
4. Actually, PHP 5.5 is not actively supported anymore, and PHP 5.6 active support expires at the end of this year (see [supported versions](http://php.net/supported-versions.php)). So I would definitely start coding things with PHP 7 in mind!

@jkuchar There are good ideas indeed in nette/html, and I can see that some of their choices confirm my gut feeling (such as accepting raw HTML strings as well as existing tag objects). @broeser It would be interesting to check what `Html::el()` does, as I suspect it does what you suggested in point 2 (unless they have a single class for self-closing and container tags, but then I doubt they choose to output `/ >` self-closing tags based solely on whether a content has been provided ot not!)

**Comment by BenMorel** [comment]
I actually had a look myself at Nette\Html source code, and found out that:
- There is a single `Html` class to act as self-closing and container tags
- They do maintain a [list of empty HTML elements](https://github.com/nette/utils/blob/master/src/Utils/Html.php#L42-L46). It starts making sense for me to have a single factory @broeser, it's indeed easier to use and more readable. We could follow this route, and also I'm starting to think that a single `Tag` class might be better (otherwise you don't know what subclass the factory is returning); we would just have to define what the methods to add content do on a self-closing tag (ignore silently, or throw exception).
- They output the `>` or `/ >` at the end of a self-closing tag based on a static [$xhtml](https://github.com/nette/utils/blob/master/src/Utils/Html.php#L39) property. I'm not personally fond of public static properties (which effectively act as global variables). We can just choose to leave it as it is though (always output `/ >`) as it's valid XHTML _and_ valid HTML5 as far as I can see.

**Comment by broeser** [comment]
I've also had a look at Nette\Html, it looks very good to me!
They keep an array of children which can either be another Html-object or a string, and while there is no support for my idea of removing elements by attribute, it could be easily extended to do so.
I think I'll use Nette\Html in my current project and see how that turns out. :)

I'll follow progress on this project as well, though. I agree on your points 2. and 4.; concerning 1. Accepting raw HTML strings is wise, but I think implicitly creating objects out of them is a good idea, that would also lower complexity on 3. significantly

Concerning self-closing tags: I'd say throwing an Exception on trying to add content is more useful, because otherwise errors might go unnoticed. Also always using /> seems like a good idea.

**Comment by BenMorel** [comment]
You are right to use Nette\Html if it suits your needs. I had not heard of it when I created this library, otherwise I would have considered it as well!

**Comment by jkuchar** [comment]
PS: Statics are there because design came form the [oldest part of the framework](https://github.com/nette/utils/commit/903b8ffdd838c66373015dedb5ae7257532630f8#diff-b6d0b2fc084aef0d4b340fa39daca7baR1) (2006). Nevertheless it is still quite practical tool.

**Comment by BenMorel** [comment]
I understand, I'm not criticizing their work, it's definitely a good framework. I'm just saying what I would _not_ like to see in Brick!
